Counter App (TASK-1)-Jhanvi Madan
am-igdtuw/MENTORSHIP-COHORT1.0 pull request #59
Opened 2023-08-24 17:22 UTC by Jhanvimadan

2023-09-02 13:05 UTC, i-am-SnehaChauhan requested changes
Screenshot or video demonstration not provided

2023-09-02 13:05 UTC, i-am-SnehaChauhan commented on Counter App (Assignment)-Jhanvi Madan
Please you provide screenshots or a video of the page.

2023-09-03 09:07 UTC, Jhanvimadan commented on Counter App (Assignment)-Jhanvi Madan
https://github.com/am-igdtuw/MENTORSHIP-COHORT1.0/assets/124586881/fa108797-cb8d-4487-9dae-d823a3b92dce

2023-09-03 19:53 UTC, Jhanvimadan commented on Counter App (Assignment)-Jhanvi Madan
Earlier my video wasn't uploading so I put the link in the code itself as comment.

2023-09-08 14:08 UTC, closed without merging