Done Assignment 2 Task 1
am-igdtuw/MENTORSHIP-COHORT1.0 pull request #60
Opened 2023-08-24 17:54 UTC by gunjanvjangra

Click Counter Code and Functioning

2023-08-25 06:04 UTC, gunjanvjangra commented
Google Drive Link for the functioning video: 
https://drive.google.com/file/d/1eddP_H9_r7rW6Dd1bywtOVQTwQTUCokf/view?usp=sharing

2023-08-26 07:13 UTC, gunjanvjangra commented
Task 2 : Clone and Additional Details of Provided Feed Page 
Done

2023-09-02 13:16 UTC, i-am-SnehaChauhan requested changes
Add Counter page code and screenshots.

2023-09-02 13:16 UTC, i-am-SnehaChauhan commented on Assignment 2/Click Counter.mp4
The counter page is not Visible. Please provide the code and the screenshots for the same

2023-09-02 13:16 UTC, i-am-SnehaChauhan commented on Assignment 1/Question.js
Late Submission

2023-09-02 13:18 UTC, i-am-SnehaChauhan approved these changes

2023-09-03 08:51 UTC, gunjanvjangra commented
Assignment 3 : Counter using functional and class component + Form to fill basic details 
Done

2023-09-08 14:05 UTC, closed without merging